# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvs_app', '0002_auto_20190916_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='nerwork',
            new_name='network',
        ),
    ]
